<?php

namespace Puml\Test\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-09 at 13:32:34.
 */
class MethodTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Method
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \Puml\Model\Method;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Puml\Model\Method::addParameter
     */
    public function testAddParameter() {
        $parameter = $this->getMock('\Puml\Model\MethodParameter');
        $this->assertSame(
            $this->object,
            $this->object->addParameter($parameter)
        );
    }

    /**
     * @covers Puml\Model\Method::getParameters
     */
    public function testGetParameters() {
        $this->assertInternalType(
            'array',
            $this->object->getParameters()
        );
        $parameter = $this->getMock('\Puml\Model\MethodParameter');
        $this->object->addParameter($parameter);
        $this->assertContains(
            $parameter,
            $this->object->getParameters()
        );

    }

    /**
     * @covers Puml\Model\Method::hasParameters
     */
    public function testHasParameters() {
        $this->assertFalse($this->object->hasParameters());
        $parameter = $this->getMock('\Puml\Model\MethodParameter');
        $this->object->addParameter($parameter);
        $this->assertTrue($this->object->hasParameters());
    }
}
