<?php

namespace Puml\Test\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-09 at 17:34:45.
 */
class MethodParameterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MethodParameter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \Puml\Model\MethodParameter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Puml\Model\MethodParameter::getName
     */
    public function testGetName() {
        $name = 'recursive';
        $this->object->setName($name);
        $this->assertSame($name, $this->object->getName());
    }

    /**
     * @covers Puml\Model\MethodParameter::setName
     */
    public function testSetName() {
        $this->assertSame(
            $this->object,
            $this->object->setName('recursive')
        );
    }

    /**
     * @covers Puml\Model\MethodParameter::getType
     */
    public function testGetType() {
        $type = 'boolean';
        $this->object->setType($type);
        $this->assertSame($type, $this->object->getType());
    }

    /**
     * @covers Puml\Model\MethodParameter::setType
     */
    public function testSetType() {
        $this->assertSame(
            $this->object,
            $this->object->setType('bolean')
        );
    }
}
