<?php

namespace Puml\Test\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-28 at 20:06:31.
 */
class ObjectItemTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ObjectItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMockForAbstractClass('\Puml\Model\ObjectItem');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Puml\Model\ObjectItem::getVisibility
     */
    public function testGetVisibility() {
        $this->assertEquals(
            \ReflectionMethod::IS_PUBLIC,
            $this->object->getVisibility()
        );
        $this->object->setVisibility(\ReflectionMethod::IS_PROTECTED);
        $this->assertEquals(
            \ReflectionMethod::IS_PROTECTED,
            $this->object->getVisibility()
        );
    }

    /**
     * @covers Puml\Model\ObjectItem::setVisibility
     */
    public function testSetVisibility() {
        $this->assertSame(
            $this->object,
            $this->object->setVisibility(\ReflectionMethod::IS_PROTECTED)
        );
    }

    /**
     * @covers Puml\Model\ObjectItem::getName
     */
    public function testGetName() {
        $this->assertNull($this->object->getName());
        $this->object->setName('stdClass');
        $this->assertEquals('stdClass', $this->object->getName());
    }

    /**
     * @covers Puml\Model\ObjectItem::setName
     */
    public function testSetName() {
        $this->assertSame(
            $this->object,
            $this->object->setName('stdClass')
        );
    }

    /**
     * @covers Puml\Model\ObjectItem::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        $this->assertNull($this->object->getType());
        $this->object->setType('boolean');
        $this->assertEquals('boolean', $this->object->getType());
    }

    /**
     * @covers Puml\Model\ObjectItem::setType
     * @todo   Implement testSetType().
     */
    public function testSetType() {
        $this->assertSame(
            $this->object,
            $this->object->setType('boolean')
        );
    }
}
